mutation CreateTransaction($input: transactionInput) {
  createTransaction(input: $input) {
    ok
    transaction {
      id
      product {
        id
        name
      }
      basePrice
      profit
      qty
      total
      verBy {
        id
        username
        position
      }
      createdAt
    }
  }
}
