mutation CreateProduct($input: productInput) {
    createproduct(input: $input) {
        ok
        product {
            id
            name
            desc
            price
            stock
            createdAt
            updatedAt
        }
    }
}