mutation CreateProduct($input: productInput) {
  createProduct(input: $input) {
    ok
    product {
      id
      name
      desc
      basePrice
      profit
      stock
      createdAt
      updatedAt
    }
    error {
      message
    }
  }
}
