mutation DeleteProduct($id: String!, $companyDetailId: ID!) {
  deleteProduct(id: $id, companyDetailId: $companyDetailId) {
    ok
    product {
      id
      name
      desc
    }
    error {
      message
    }
  }
}
