query GetCompanyDetails {
  CompanyDetails {
    ok
    companyDetail {
      id
      name
      npwp
      balance
      revenue
      netProfit
      asset {
        id
        name
        assetCode
        boughtSince
        boughtPrice
        desc
      }
    }
  }
}
