query GetCompanyDetails {
  CompanyDetails {
    ok
    companyDetail {
      id
      name
      npwp
      balance
      revenue
      netProfit
      tangibleAsset {
        id
        name
        boughtSince
        boughtPrice
        depCategory
        depAmount
        timePeriod
        desc
      }
      intangibleAsset {
        id
        name
        boughtSince
        boughtPrice
        depCategory
        depAmount
        timePeriod
        desc
      }
      propertyAsset {
        id
        name
        boughtSince
        boughtPrice
        depCategory
        depAmount
        timePeriod
        desc
      }
      taxReport {
        id
        name
        nptn
        amount
        isPaid
        dueDate
      }
    }
    error {
      message
    }
  }
}
