query GetExpense {
  Expenses {
    ok
    expense {
      id
      name
      expCategory {
        id
        name
      }
      amount
      verBy {
        id
        username
      }
      createdAt
    }
    error {
      message
    }
  }
}
