query GetProductShortage($stock: Int, $sort: SORTING) {
  Products(stock: $stock, sort: $sort) {
    ok
    product {
      id
      name
      desc
      stock
      basePrice
      profit
      createdAt
      updatedAt
    }
    error {
      message
    }
  }
}
