query GetRecentTransactions($isRecent: Boolean) {
  Transactions(isRecent: $isRecent) {
    ok
    transaction {
      id
      product {
        id
        name
      }
      basePrice
      profit
      qty
      total
      verBy {
        id
        email
        username
        position
      }
      createdAt
    }
    error {
      message
    }
  }
}
