mutation Login($input: userLogin) {
    login(input: $input) {
        ok
        user {
            id
            npwp
            username
            position
            address
            phoneNumber
            accessToken
        }
        error {
            message
        }
    }
}