mutation Login($input: userLogin) {
    login(input: $input) {
        ok
        user {
            id
            email
            username
            position
            accessToken
        }
    }
}