query ProductShortage($input: String) {
  Products(input: $input) {
    ok
    product {
      id
      name
      desc
      stock
      basePrice
      profit
    }
    error {
      message
    }
  }
}
