mutation updateCompanyDetail($input: companyDetailInput) {
  updateCompanyDetail(input: $input) {
    ok
    companyDetail {
      id
      name
      npwp
      balance
      revenue
      netProfit
      tangibleAsset {
        id
        name
        boughtSince
        boughtPrice
        depCategory
        depAmount
        timePeriod
        desc
      }
      intangibleAsset {
        id
        name
        boughtSince
        boughtPrice
        depCategory
        depAmount
        timePeriod
        desc
      }
      propertyAsset {
        id
        name
        boughtSince
        boughtPrice
        depCategory
        depAmount
        timePeriod
        desc
      }
    }
    error {
      message
    }
  }
}
