mutation updateUser($input: userInput) {
  updateUser(input: $input) {
    ok
    user {
      id
      email
      username
      npwp
      position
      address
      phoneNumber
      accessToken
    }
    error {
      message
    }
  }
}
